name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List files
        run: ls

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Run python challenge
        run: python challenge1/add_subtract.py
        
      - name: Run python unittest
        run: python challenge1/unit_test.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: | 
          docker build . --file ./challenge2/Docker/Dockerfile --tag git-image:$(date +%s)

          docker run . --file ./challenge2/Docker/Dockerfile --tag git-image:$(date +%s)

